-- AlterTable
ALTER TABLE "NoteTopic" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "id" TEXT NOT NULL DEFAULT '',
ADD CONSTRAINT "NoteTopic_pkey" PRIMARY KEY ("id");
