# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Console

on:
  push:
    branches:
      - main
    paths:
      - 'apps/console/**'
      - '.github/workflows/build-console.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/console/**'
      - '.github/workflows/build-console.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.x.x

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm i
      - name: Test and Build
        working-directory: ./apps/console
        run: |
          pnpm run build
        env:
          CI: true
